# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
# en:
#   languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
#zh:
#  languageCode: zh-Hans
#  contentDir: content/zh
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1

pt:
  languageCode: pt-PT
  title: "VCNAAS 2026 - LADO A LADO"
  weight: 1

en:
  languageCode: en
  title: "VCNAAS 2026 - SIDE BY SIDE"
  weight: 1

es:
  languageCode: es
  title: "VCNAAS 2026 - LADO A LADO"
  weight: 1
  

fr:
  languageCode: fr
  title: "VCNAAS 2026 - CÔTE À CÔTE"
  weight: 1
  
